"""Add timestamp to Match model

Revision ID: 2782ac0e5130
Revises: bcd07e62f838
Create Date: 2025-11-05 23:48:38.513613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2782ac0e5130'
down_revision = 'bcd07e62f838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(), nullable=False),
    sa.Column('kda', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_timestamp'))

    op.drop_table('match')
    # ### end Alembic commands ###
