"""Initial migration

Revision ID: 27d6d5e86cd4
Revises: 
Create Date: 2025-10-28 20:11:17.913127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d6d5e86cd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(), nullable=False),
    sa.Column('kda', sa.String(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
