"""create match table

Revision ID: 2dfc8f25e6e0
Revises: 
Create Date: 2025-11-08 18:28:41.575957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfc8f25e6e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('champion', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('time_dead', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('neutral_cs', sa.Integer(), nullable=False),
    sa.Column('enemy_jungle_cs', sa.Integer(), nullable=False),
    sa.Column('ally_jungle_cs', sa.Integer(), nullable=False),
    sa.Column('vision', sa.Integer(), nullable=False),
    sa.Column('wards_placed', sa.Integer(), nullable=False),
    sa.Column('wards_killed', sa.Integer(), nullable=False),
    sa.Column('dragons', sa.Integer(), nullable=False),
    sa.Column('barons', sa.Integer(), nullable=False),
    sa.Column('heralds', sa.Integer(), nullable=False),
    sa.Column('towers', sa.Integer(), nullable=False),
    sa.Column('inhibitors', sa.Integer(), nullable=False),
    sa.Column('team_kills', sa.Integer(), nullable=False),
    sa.Column('team_damage', sa.Integer(), nullable=False),
    sa.Column('team_gold', sa.Integer(), nullable=False),
    sa.Column('team_vision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_timestamp'), ['timestamp'], unique=False)

    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_timestamp'))

    op.drop_table('match')
    # ### end Alembic commands ###
