"""add_match_timeline_summary_table

Revision ID: 853f56d15357
Revises: c5a7168d23d9
Create Date: 2025-11-09 23:26:34.472609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853f56d15357'
down_revision = 'c5a7168d23d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_timeline_summary',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('early_dominance_score', sa.Float(), nullable=True),
    sa.Column('midgame_swing_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('level_6_timestamp', sa.Integer(), nullable=True),
    sa.Column('level_11_timestamp', sa.Integer(), nullable=True),
    sa.Column('level_16_timestamp', sa.Integer(), nullable=True),
    sa.Column('biggest_spike', sa.Float(), nullable=True),
    sa.Column('biggest_throw', sa.Float(), nullable=True),
    sa.Column('roam_score', sa.Float(), nullable=True),
    sa.Column('kill_positions', sa.JSON(), nullable=True),
    sa.Column('objective_presence', sa.JSON(), nullable=True),
    sa.Column('comeback_type', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id', 'puuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_timeline_summary')
    # ### end Alembic commands ###
