"""Add puuid column to Match table

Revision ID: bcd07e62f838
Revises: 27d6d5e86cd4
Create Date: 2025-10-28 20:30:34.033093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd07e62f838'
down_revision = '27d6d5e86cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puuid', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('puuid')

    # ### end Alembic commands ###
