"""add timeline + events tables

Revision ID: c5a7168d23d9
Revises: 2dfc8f25e6e0
Create Date: 2025-11-09 23:09:44.776204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a7168d23d9'
down_revision = '2dfc8f25e6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('killer_champion', sa.String(), nullable=True),
    sa.Column('victim_champion', sa.String(), nullable=True),
    sa.Column('assisting_champions', sa.JSON(), nullable=True),
    sa.Column('objective_type', sa.String(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'puuid', 'timestamp', 'event_type', name='uq_match_puuid_timestamp_event')
    )
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_events_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_events_puuid'), ['puuid'], unique=False)

    op.create_table('match_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('jungle_cs', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('cc_time', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('gold_diff', sa.Integer(), nullable=False),
    sa.Column('xp_diff', sa.Integer(), nullable=False),
    sa.Column('cs_diff', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'puuid', 'frame_index', name='uq_match_puuid_frame')
    )
    with op.batch_alter_table('match_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_timeline_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_timeline_puuid'), ['puuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_timeline_puuid'))
        batch_op.drop_index(batch_op.f('ix_match_timeline_match_id'))

    op.drop_table('match_timeline')
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_events_puuid'))
        batch_op.drop_index(batch_op.f('ix_match_events_match_id'))

    op.drop_table('match_events')
    # ### end Alembic commands ###
